# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlerrecord',
            name='status',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
