# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160501_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlerrecord',
            name='updated_time',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
