# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_crawlerrecord_updated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlerrecord',
            name='task_id',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
