# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_crawlerrecord_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('link', models.TextField()),
                ('phone', models.CharField(max_length=255)),
                ('website', models.TextField()),
                ('category', models.TextField()),
                ('likes', models.CharField(max_length=5)),
                ('email', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('keyword', models.CharField(max_length=255)),
            ],
        ),
    ]
