# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_facebookpage_crawl_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookpage',
            name='pid',
            field=models.CharField(max_length=50),
        ),
    ]
