# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20160509_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerSiteMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_row_id', models.IntegerField()),
                ('crawler_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CrawlerRecord')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Site')),
            ],
        ),
    ]
