# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20160509_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookpage',
            name='crawl_id',
        ),
    ]
