# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_facebookpage_crawl_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlerrecord',
            name='keyword',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
