# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20160518_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripadvisorcat',
            name='cat',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='tripadvisorlocation',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
